CREATE USER {PGUSER};
ALTER USER {PGUSER} with login;
ALTER USER {PGUSER} with password '{PGUSER_PASSWD}';
CREATE DATABASE brane_main WITH ENCODING 'utf8';
ALTER DATABASE brane_main OWNER TO {PGUSER};

