[entryPoints]
  [entryPoints.web]
    address = ":80"
    address =":443"

[api]
  insecure = true

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    watch = true
    exposedByDefault = false